version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "19000:9000"  # MinIO API port pada host 19000
      - "19001:9001"  # MinIO console port pada host 19001
    environment:
      MINIO_ROOT_USER: minioadmin  # Default root user
      MINIO_ROOT_PASSWORD: minioadmin  # Default root password
    volumes:
      - minio_data:/data  # Persistent storage for MinIO data
    command: server /data --console-address ":9001"

volumes:
  minio_data: